### ISSUE TITLE
Problems running wflow example

### ISSUE THREAD

**Issue by josevalles7** [openstreams/wflow#41] opened 2020-11-22 14:58 UTC
Hello, 
I have created a conda environment and I have installed wflow according to the documentation. However, when I wanted to check if the installation was correct, using the 
`python -m wflow.wflow_sbm -C wflow_rhine_sbm -R testing`

I got the following error: 

`ERROR:root:  File "C:\Anaconda3\envs\wflow\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda3\envs\wflow\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\wflow\lib\site-packages\wflow\wflow_sbm.py", line 75, in <module>
    from wflow.wflow_funcs import *
  File "C:\Anaconda3\envs\wflow\lib\site-packages\wflow\wflow_funcs.py", line 32, in <module>
    from numba.errors import NumbaPendingDeprecationWarning

ERROR:root:<class 'ModuleNotFoundError'>: No module named 'numba.errors' `

How can I fix this issue? 

Thanks for your reply

**Comment by visr** [comment] 2020-11-22 16:22
Hi, unfortunately this was caused by a change in numba. We have updated the code in #34 but this is currently not yet in the latest release. Would it be possible to, after activating your `wflow` conda environment, do `conda install numba=0.48`, and see if the error message dissappears?

**Comment by josevalles7** [comment] 2020-11-23 11:49
Hi... 
It works perfectly!! the error message dissappears
Thanks for your reply!

**Comment by visr** [comment] 2020-11-23 12:08
Glad it worked for you! We'll be making a new patch release shortly such that this extra step is not needed anymore.

**Comment by visr** [comment] 2020-11-26 11:21
This fix in now also available in the bugfix release 2020.1.2: https://github.com/openstreams/wflow/releases/tag/2020.1.2, so I'm closing this issue. Thanks for the report!

**Closed by visr** 2020-11-26 11:21 UTC
