### ISSUE TITLE
Problem with -I command-line option

### ISSUE THREAD

**Issue by JankoLancer** [openstreams/wflow#16] opened 2018-03-20 18:48 UTC
I want to use -I command-line option to start model with default initial conditions but in that case I get message:
"wflow_sbm - ERROR - problem while reading state variable from disk: .../examples/wflow_rhine_sbm/instate/SurfaceRunoff.map Suggest to use the -I option to restart"

but I already used -I option, I start script like this:

python c:\Anaconda\Scripts\wflow_sbm.py -C wflow_rhine_sbm -R testing -I

Do you know what is the problem?

**Comment by visr** [comment] 2018-11-07 21:12
Sorry for taking so long to get back to you. I'm not sure what is happening here, but on the 2018.1 version we released today (or master), I cannot reproduce, it is running fine if I do this in the examples directory:
```
python -m wflow.wflow_sbm -C wflow_rhine_sbm -R testing -I
```

**Comment by visr** [comment] 2018-11-20 19:30
I'll close this for now, feel free to reopen it if you are still having issues.

**Closed by visr** 2018-11-20 19:30 UTC

**Comment by DanielTollenaar** [comment] 2018-11-20 19:44
Hi Martijn,

If I am not mistaken this issue has to do with an incomplete set of initial
state maps. Remove one map from the instate folder of your hbv-model and
you probably get the same message.

Reinitalisation, as the error-message suggests, fixes the problem though.

Cheers!

Op di 20 nov. 2018 om 20:30 schreef Martijn Visser <notifications@github.com

**Comment by DanielTollenaar** [comment] 2018-11-20 19:46
Sorry It's rhine-model not hbv model. It's an SBM-model.

Op di 20 nov. 2018 om 20:44 schreef Daniel Tollenaar <
daniel.tollenaar@gmail.com>:
